version: 2
jobs:
  build:
    docker:
      - image: busybox
    working_directory: /home/nickleefly/nginx-proxy-google
    steps:
      - run: echo doing nothing.

  ###########################
  #### ubuntu-14.04-XXL #####
  ###########################
  ubuntu-14.04-XXL:
    machine:
      docker_layer_caching: true
    working_directory: /home/nickleefly/nginx-proxy-google
    environment:
      IMAGE_REPO: nickleefly/nginx-proxy-google
      TARGET: ubuntu-14.04-XXL
      _TARGET: ubuntu-14_04-XXL
    steps:
      - checkout
      - run: echo -n "$TARGET-$CIRCLE_BUILD_NUM-$(git rev-parse --short HEAD)" > _tag
      - run: echo "Building $IMAGE_REPO:$(cat _tag)"
      - run:
          command: |
            docker build \
            $NO_CACHE \
            --build-arg IMAGE_TAG=$(cat _tag) \
            -t $IMAGE_REPO:$(cat _tag) \
            .

      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
