version: 2
jobs:
  build:
    docker:
     - image: circleci/node:9.8.0-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true

      # build the application image
      - run:
          name: Build Docker image
          command: |
            docker build -t nginx-proxy-google .

      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d -p 8080:80 --name nginx nginx-proxy-google
