version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
        # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build the application image
      - run:
          name: Build Docker image
          command: |
            docker build -t nginx-proxy-google .

      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d -p 8080:80 nginx-proxy-google --name nginx
            docker exec nginx curl --retry 10 --retry-connrefused http://localhost:8080
