version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build the application image
      - run:
          name: Build Docker image
          command: |
            docker build -t nginx-proxy-google .

      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run -d -p 8080:80 nginx-proxy-google --name nginx
            docker exec nginx curl --retry 10 --retry-connrefused http://localhost:8080
